### ISSUE TITLE
Can not find the module

### ISSUE THREAD

**Issue by DRjy** [ZJU-Robotics-Lab/DPCN#1]
`import imreg_dft.utils as utils`
File "/DPCN-master/fft/dft_test.py", line 16, in <module>
import imreg_dft.utils as utils
ModuleNotFoundError: No module named 'imreg_dft'

Is there some files not uploaded? Thanks in advance.

**Comment by jessychen1016** [comment]
Hi there,
The file dft_test.py was a testing version during the set-up stage of DPCN which is no longer needed.
However, if you are trying to figure out how dft works, you might want to consult with unet/pytorch_DPCN.py

Jessy
