### ISSUE TITLE
demo、checkpoints not provided in this repo

### ISSUE THREAD

**Issue by Sly-Guo** [ZJU-Robotics-Lab/DPCN#2]
Without demo data, how can we quickly rerun the detect.py

**Comment by jessychen1016** [comment]
Hi Sly,

Thank you for the issue! The checkpoint is provided as a google drive link in README, also fyb as follows: https://drive.google.com/file/d/1GZ8hz3cfaBP7F7KEdQK7M_WcwOM1GF6z/view?usp=sharing.

The demo folder was mistakenly ignored by thr .gitignore and we will upload it real quick :) (probably by tomorrow)

BTW, if you urgently want to test it, you can run the `python trainDPCN.py --simulation` to generate a bunch of simulated data, and test the detect.py with them together with the downloaded checkpoint. 

Jessy
